### ISSUE TITLE
Benchmark.h missing

### ISSUE THREAD

**Issue by Arthur111** [bwesterb/armed-keccak#1]
Hello,

Seems benchmark.h is missing : 

benchmark.cxx:1:10: fatal error: 'benchmark/benchmark.h' file not found
#include <benchmark/benchmark.h>

during : make benchmark

**Comment by bwesterb** [comment]
You need to have [Google Benchmark](https://github.com/google/benchmark) installed.

**Comment by Arthur111** [comment]
Ok so i'll do my own benchmark.
